name: Test

on:
  pull_request:
    branches:
      - main
  schedule:
    - cron: '0 22 * * 3'
  workflow_call:

permissions:
  contents: read

jobs:
  test:
    name: Test
    strategy:
      matrix:
        node-version:
          - '20.9'
          - '18.17'
          - '16.20'
          - '14.16'
        os:
          - macos-latest
          - ubuntu-latest
          - windows-latest
    runs-on: "${{ matrix.os }}"
    steps:
      - name: Install Rosetta
        if: ${{ matrix.os == 'macos-latest' && matrix.node-version == '14.16' }}
        run: /usr/sbin/softwareupdate --install-rosetta --agree-to-license
      - name: Checkout
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
      - name: Setup Node.js
        uses: actions/setup-node@1d0ff469b7ec7b3cb9d8673fde0c81c44821de2a # v4.2.0
        with:
          node-version: "${{ matrix.node-version }}"
          cache: 'yarn'
          architecture: ${{ matrix.os == 'macos-latest' && matrix.node-version == '14.16' && 'x64' || env.RUNNER_ARCH }}
      - name: Install
        run: yarn install --frozen-lockfile
      - name: Test
        run: yarn test
